"""auto-vote

Revision ID: 27cf1c67b02e
Revises: 62a34ff3c976
Create Date: 2022-11-22 18:59:08.976788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cf1c67b02e'
down_revision = '62a34ff3c976'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('published', sa.Boolean(), server_default='True', nullable=True))
    op.drop_column('posts', 'publshed')
    op.drop_column('posts', 'Title')
    op.alter_column('users', 'email',existing_type=sa.VARCHAR(),nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('posts', sa.Column('Title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('publshed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('posts', 'published')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
